# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproxy.proto\"\x1c\n\x0cWriteRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\r\n\x0bReadRequest\"\x1c\n\x0cReadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2[\n\x0cProxyService\x12&\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEREQUEST']._serialized_start=15
  _globals['_WRITEREQUEST']._serialized_end=43
  _globals['_WRITERESPONSE']._serialized_start=45
  _globals['_WRITERESPONSE']._serialized_end=77
  _globals['_READREQUEST']._serialized_start=79
  _globals['_READREQUEST']._serialized_end=92
  _globals['_READRESPONSE']._serialized_start=94
  _globals['_READRESPONSE']._serialized_end=122
  _globals['_PROXYSERVICE']._serialized_start=124
  _globals['_PROXYSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
