# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"H\n\x14\x41ppendEntriesRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x03 \x03(\t\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x11\n\x0fGetStateRequest\"!\n\x10GetStateResponse\x12\r\n\x05state\x18\x01 \x01(\t\"8\n\x12RequestVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x32\xb8\x01\n\x0bRaftService\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12/\n\x08GetState\x12\x10.GetStateRequest\x1a\x11.GetStateResponse\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDENTRIESREQUEST']._serialized_start=14
  _globals['_APPENDENTRIESREQUEST']._serialized_end=86
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=88
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=142
  _globals['_GETSTATEREQUEST']._serialized_start=144
  _globals['_GETSTATEREQUEST']._serialized_end=161
  _globals['_GETSTATERESPONSE']._serialized_start=163
  _globals['_GETSTATERESPONSE']._serialized_end=196
  _globals['_REQUESTVOTEREQUEST']._serialized_start=198
  _globals['_REQUESTVOTEREQUEST']._serialized_end=254
  _globals['_REQUESTVOTERESPONSE']._serialized_start=256
  _globals['_REQUESTVOTERESPONSE']._serialized_end=313
  _globals['_RAFTSERVICE']._serialized_start=316
  _globals['_RAFTSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
